name: Build LinuxDwarfPack package

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxml-libxml-perl libxml-xslt-perl libxml-filter-xslt-perl mercurial help2man git openjdk-8-jre libncurses5-dev zlib1g-dev lib32z1-dev mesa-common-dev gcc-multilib g++-multilib cmake dos2unix tcl autoconf gperf bison flex gawk libtool libsdl-dev libsdl-image1.2 libsdl-ttf2.0-0 texinfo ninja-build qt5-qmake qttools5-dev-tools qt5-default libqt5svg5-dev qt5-image-formats-plugins qtbase5-dev qtdeclarative5-dev python3-tk

    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Name package
      id: slug
      run: |
        echo "PKG_NAME=LinuxDwarfPack-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "DIR_NAME=LinuxDwarfPack-$(source version.sh)" >> $GITHUB_ENV

    - name: Build
      run: |
        autoconf && ./configure --prefix=$PWD && make install
        echo "CT_LOG_PROGRESS_BAR=n" >> .config
        ./bin/lnp-forge build
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build.log
        path: build.log
      if: ${{ failure() }}

    - name: Build tar.gz
      run: |
        source .config && mv .build/src/lnp-${CT_LNP_VERSION} ${{ env.DIR_NAME }}
        tar cjf ${{ env.DIR_NAME }}.tbz2 ${{ env.DIR_NAME }}
    
    - name: Upload .tar package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.tbz2
        path: ${{ env.DIR_NAME }}.tbz2
    
    - name: Install packaging dependencies
      run: |
        sudo apt-get install ruby ruby-dev rubygems build-essential bsdtar
        sudo gem install --no-document fpm

    - name: Fix world writable dirs
      run: |
        chmod go-w $HOME
        sudo chmod -R go-w /home/linuxbrew
        sudo chmod -R go-w /home/runner
        sudo chmod -R go-w /usr/share
        sudo chmod -R go-w /opt

    - name: Build AppImage, deb, xz, rpm packages
      run: |
        echo "CT_APPIMAGE=y" >> .config
        echo "CT_DEBIAN=y" >> .config
        echo "CT_ARCH=y" >> .config
        echo "CT_RPM=y" >> .config
        ./bin/lnp-forge clean build
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build.log
        path: build.log
      if: ${{ failure() }}

    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.AppImage
        path: Dwarf_Fortress-*-x86_64.AppImage

    - name: Upload .deb package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.deb
        path: linux-dwarf-pack_*_amd64.deb

    - name: Upload .xz package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.pkg.tar.xz
        path: linux-dwarf-pack-*-1-x86_64.pkg.tar.xz

    - name: Upload .rpm package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PKG_NAME }}.rpm
        path: linux-dwarf-pack-*-1.x86_64.rpm
